# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1128f0bc9b3a12d258242b8f0c27571a63d3db9f497b9601092437775f58aa61ea9405ffb21b197c2e138de099deec9ed6e9753e500fd34ce3f731ad4a04620e

test:
  secret_key_base: 4bd54f85246b17036fd59efba8899ca3b9701348c1bd310ce34045ff63337bfe26c2a5e7413e1e1e4fd0840665bdb3fa94683596468506002eb70b66084a5ea7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
